import { MigrationInterface, QueryRunner } from "typeorm";

export class Ingredients1601299206153 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        insert into ingredient (name) values ('Mangue');
        insert into ingredient (name) values ('Palourde');
        insert into ingredient (name) values ('Tomate');
        insert into ingredient (name) values ('Salsifis');
        insert into ingredient (name) values ('Argousier');
        insert into ingredient (name) values ('Crosse de fougère');
        insert into ingredient (name) values ('Noisette');
        insert into ingredient (name) values ('Poire');
        insert into ingredient (name) values ('Pomme de terre');
        insert into ingredient (name) values ('Pomme de terre');
        insert into ingredient (name) values ('Maïs');
        insert into ingredient (name) values ('Betterave');
        insert into ingredient (name) values ('Grenade');
        insert into ingredient (name) values ('Choux de Bruxelles');
        insert into ingredient (name) values ('Wakamé');
        insert into ingredient (name) values ('Noix du Brésil');
        insert into ingredient (name) values ('Oignon');
        insert into ingredient (name) values ('Roquette');
        insert into ingredient (name) values ('Chou-fleur');
        insert into ingredient (name) values ('Canneberge');
        insert into ingredient (name) values ('Noix de cajou');
        insert into ingredient (name) values ('Chou');
        insert into ingredient (name) values ('Cardamome');
        insert into ingredient (name) values ('Estragon');
        insert into ingredient (name) values ('Poireau');
        insert into ingredient (name) values ('Brocoli');
        insert into ingredient (name) values ('Combava');
        insert into ingredient (name) values ('Physalis');
        insert into ingredient (name) values ('Physalis');
        insert into ingredient (name) values ('Cornichon');
        insert into ingredient (name) values ('Pitaya');
        insert into ingredient (name) values ('Citrouille');
        insert into ingredient (name) values ('Soda');
        insert into ingredient (name) values ('Griottes');
        insert into ingredient (name) values ('Cumin');
        insert into ingredient (name) values ('Noix de Macadamia');
        insert into ingredient (name) values ('Vanille');
        insert into ingredient (name) values ('Olive');
        insert into ingredient (name) values ('maca');
        insert into ingredient (name) values ('Kiwi');
        insert into ingredient (name) values ('Chou chinois');
        insert into ingredient (name) values ('Sauge');
        insert into ingredient (name) values ('Rhubarbe');
        insert into ingredient (name) values ('Huile de palme');
        insert into ingredient (name) values ('tofu');
        insert into ingredient (name) values ('Airelles');
        insert into ingredient (name) values ('Pomme');
        insert into ingredient (name) values ('Vivaneau');
        insert into ingredient (name) values ('huiles végétales');
        insert into ingredient (name) values ('simili-viande');
        insert into ingredient (name) values ('Saumon');
        insert into ingredient (name) values ('Amande');
        insert into ingredient (name) values ('Cerise');
        insert into ingredient (name) values ('Endive');
        insert into ingredient (name) values ('Marron');
        insert into ingredient (name) values ('Kumquat');
        insert into ingredient (name) values ('Banane');
        insert into ingredient (name) values ('Seigle');
        insert into ingredient (name) values ('Céleri');
        insert into ingredient (name) values ('Riz sauvage');
        insert into ingredient (name) values ('Chou');
        insert into ingredient (name) values ('Noix');
        insert into ingredient (name) values ('Orange');
        insert into ingredient (name) values ('Jujube');
        insert into ingredient (name) values ('Oeuf');
        insert into ingredient (name) values ('Châtaigne (marron)');
        insert into ingredient (name) values ('Tapioca');
        insert into ingredient (name) values ('Ananas');
        insert into ingredient (name) values ('Pistache');
        insert into ingredient (name) values ('Persil');
        insert into ingredient (name) values ('Basilic');
        insert into ingredient (name) values ('Moule');
        insert into ingredient (name) values ('Châtaigne (marron)');
        insert into ingredient (name) values ('Salsifis');
        insert into ingredient (name) values ('Navet');
        insert into ingredient (name) values ('Igname');
        insert into ingredient (name) values ('Tilapia');
        insert into ingredient (name) values ('Cacao');
        insert into ingredient (name) values ('Radis');
        insert into ingredient (name) values ('Soda');
        insert into ingredient (name) values ('Poireau');
        insert into ingredient (name) values ('Kaki');
        insert into ingredient (name) values ('Fraise');
        insert into ingredient (name) values ('Blé');
        insert into ingredient (name) values ('Seitan');
        insert into ingredient (name) values ('Choux de Bruxelles');
        insert into ingredient (name) values ('Banane');
        insert into ingredient (name) values ('Mouton');
        insert into ingredient (name) values ('Pain');
        insert into ingredient (name) values ('Tilapia');
        insert into ingredient (name) values ('Fromage');
        insert into ingredient (name) values ('Mangue');
        insert into ingredient (name) values ('Canneberge');
        insert into ingredient (name) values ('Luzerne');
        insert into ingredient (name) values ('Miel');
        insert into ingredient (name) values ('Raifort');
        insert into ingredient (name) values ('Laitue');
        insert into ingredient (name) values ('Petits pois');
        `);
  }

  public async down(_: QueryRunner): Promise<void> {}
}
